#!/usr/bin/env bash
# Idempotent Rope server installer for Ubuntu LTS / Debian (x86_64 / arm64).
# Installs rope-server plus coturn on the same host (TURN / TURNS).
set -euo pipefail

BINARY=""
HOST=""
PORT="8443"
UPGRADE=0
REINSTALL=0
PRINT_TURN_CONF=0
DATA_DIR="/var/lib/rope"
ETC_DIR="/etc/rope"
BIN_DIR="/opt/rope/bin"
SERVICE_USER="rope"
TURN_PORT="3478"
TURNS_PORT="443"
TURN_SECRET=""
RELAY_MIN="49152"
RELAY_MAX="49311"

usage() {
  echo "usage: $0 --binary /path/to/rope-server --host <ip-or-dns> [--port 8443] [--upgrade|--reinstall]"
  echo "       $0 --print-turn-conf --host <ip-or-dns> [--turns-port 443|5349] [--secret X]"
  exit 2
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --binary) BINARY="$2"; shift 2 ;;
    --host) HOST="$2"; shift 2 ;;
    --port) PORT="$2"; shift 2 ;;
    --upgrade) UPGRADE=1; shift ;;
    --reinstall) REINSTALL=1; shift ;;
    --print-turn-conf) PRINT_TURN_CONF=1; shift ;;
    --turns-port) TURNS_PORT="$2"; shift 2 ;;
    --turn-port) TURN_PORT="$2"; shift 2 ;;
    --secret) TURN_SECRET="$2"; shift 2 ;;
    *) usage ;;
  esac
done

is_ipv4() { [[ "$1" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; }

local_ipv4() {
  ip -4 route get 1.1.1.1 2>/dev/null | awk '{for (i = 1; i <= NF; i++) if ($i == "src") { print $(i + 1); exit }}'
}

resolve_ipv4() {
  local name="$1"
  if is_ipv4 "$name"; then
    echo "$name"
    return
  fi
  getent ahostsv4 "$name" 2>/dev/null | awk '{ print $1; exit }'
}

external_ip_line() {
  local pub localip
  pub="$(resolve_ipv4 "$HOST")"
  localip="$(local_ipv4 || true)"
  if [[ -n "$pub" && -n "$localip" && "$pub" != "$localip" ]]; then
    echo "external-ip=${pub}/${localip}"
  elif [[ -n "$pub" ]]; then
    echo "external-ip=${pub}"
  fi
}

render_turnserver_conf() {
  local ext_line cert_dir
  ext_line="$(external_ip_line)"
  cert_dir="${ETC_DIR}/turn-tls"
  local pub
  pub="$(resolve_ipv4 "$HOST")"
  local allowed=""
  if [[ -n "$pub" ]]; then
    allowed="allowed-peer-ip=${pub}"
  fi
  local tls_line=""
  if [[ -n "${TURNS_PORT}" && "${TURNS_PORT}" != "0" ]]; then
    tls_line="tls-listening-port=${TURNS_PORT}"
  fi
  cat <<EOF
# Generated by Rope installer. HMAC secret matches turn_secret in ${ETC_DIR}/config.json.
listening-ip=0.0.0.0
listening-port=${TURN_PORT}
${tls_line}
${ext_line}
${allowed}
min-port=${RELAY_MIN}
max-port=${RELAY_MAX}
realm=rope
server-name=rope
fingerprint
lt-cred-mech
use-auth-secret
static-auth-secret=${TURN_SECRET}
cert=${cert_dir}/cert.pem
pkey=${cert_dir}/key.pem
no-tlsv1
no-tlsv1_1
no-cli
no-multicast-peers
simple-log
denied-peer-ip=0.0.0.0-0.255.255.255
denied-peer-ip=10.0.0.0-10.255.255.255
denied-peer-ip=100.64.0.0-100.127.255.255
denied-peer-ip=127.0.0.0-127.255.255.255
denied-peer-ip=169.254.0.0-169.254.255.255
denied-peer-ip=172.16.0.0-172.31.255.255
denied-peer-ip=192.0.0.0-192.0.0.255
denied-peer-ip=192.0.2.0-192.0.2.255
denied-peer-ip=192.168.0.0-192.168.255.255
denied-peer-ip=198.18.0.0-198.19.255.255
denied-peer-ip=198.51.100.0-198.51.100.255
denied-peer-ip=203.0.113.0-203.0.113.255
denied-peer-ip=::1
stale-nonce=600
EOF
}

if [[ "$PRINT_TURN_CONF" -eq 1 ]]; then
  [[ -n "$HOST" ]] || usage
  [[ -n "$TURN_SECRET" ]] || TURN_SECRET="test-secret"
  render_turnserver_conf
  exit 0
fi

[[ -n "$BINARY" && -x "$BINARY" && -n "$HOST" ]] || usage

if [[ "$(id -u)" -ne 0 ]]; then
  echo "run as root" >&2
  exit 1
fi

port_in_use() {
  local p="$1"
  if command -v ss >/dev/null 2>&1; then
    ss -lntn 2>/dev/null | awk '{print $4}' | grep -Eq "[.:]${p}$"
  elif command -v netstat >/dev/null 2>&1; then
    netstat -lnt 2>/dev/null | grep -Eq "[.:]${p} "
  else
    return 1
  fi
}

# True if something other than coturn/turnserver already owns the TCP port.
foreign_tcp_port() {
  local p="$1"
  local line
  if ! command -v ss >/dev/null 2>&1; then
    port_in_use "$p"
    return
  fi
  line="$(ss -lntp 2>/dev/null | awk -v p=":${p}" '$4 ~ p"$" { print; exit }')"
  [[ -z "$line" ]] && return 1
  if echo "$line" | grep -Eqi 'turnserver|coturn'; then
    return 1
  fi
  return 0
}

json_get() {
  python3 -c 'import json,sys; print(json.load(open(sys.argv[1])).get(sys.argv[2],"") or "")' "$1" "$2"
}

write_ice_config() {
  local path="$1" host="$2" secret="$3" turn_port="$4" turns_port="$5"
  python3 - "$path" "$host" "$secret" "$turn_port" "$turns_port" <<'PY'
import json, sys
path, host, secret, turn_port, turns_port = sys.argv[1], sys.argv[2], sys.argv[3], int(sys.argv[4]), int(sys.argv[5])
with open(path) as f:
    cfg = json.load(f)
cfg["public_host"] = host
if not cfg.get("turn_secret"):
    cfg["turn_secret"] = secret
cfg["turn_port"] = turn_port
cfg["turns_port"] = turns_port
with open(path, "w") as f:
    json.dump(cfg, f, indent=2)
    f.write("\n")
PY
}

write_turn_status() {
  local ok="$1" err="$2" listen="$3" ext="$4"
  python3 - "$ETC_DIR/turn-status.json" "$ok" "$err" "$TURN_PORT" "$TURNS_PORT" "$listen" "$ext" <<'PY'
import json, sys
path, ok, err, turn_port, turns_port, listen, ext = sys.argv[1:8]
doc = {
    "ok": ok in ("1", "true", "True"),
    "error": err,
    "turn_port": int(turn_port or 0),
    "turns_port": int(turns_port or 0),
    "listen": listen,
    "external_ip": ext,
}
with open(path, "w") as f:
    json.dump(doc, f, indent=2)
    f.write("\n")
PY
  chown root:"$SERVICE_USER" "$ETC_DIR/turn-status.json" 2>/dev/null || true
  chmod 644 "$ETC_DIR/turn-status.json"
}

choose_turns_port() {
  # Prefer 443 when it is free (or already ours). Caddy/nginx → 5349.
  if foreign_tcp_port 443; then
    TURNS_PORT="5349"
  else
    TURNS_PORT="443"
  fi
  if [[ "$TURNS_PORT" == "5349" ]] && foreign_tcp_port 5349; then
    TURNS_PORT="0"
  fi
}

if ! id -u "$SERVICE_USER" >/dev/null 2>&1; then
  useradd --system --home "$DATA_DIR" --shell /usr/sbin/nologin "$SERVICE_USER"
fi

mkdir -p "$BIN_DIR" "$DATA_DIR" "$ETC_DIR/tls"
install -o root -g root -m 0755 "$BINARY" "$BIN_DIR/rope-server"

already_installed=0
if [[ -f "$ETC_DIR/config.json" || -f "$DATA_DIR/data.db" ]]; then
  already_installed=1
fi

if [[ "$REINSTALL" -eq 1 && "$already_installed" -eq 1 ]]; then
  systemctl stop rope 2>/dev/null || true
  rm -f "$DATA_DIR/data.db" "$DATA_DIR/data.db-wal" "$DATA_DIR/data.db-shm"
  rm -f "$ETC_DIR/config.json"
  echo "wiped previous Rope data (owner, members, mailbox)"
  already_installed=0
fi

if [[ ! -f "$ETC_DIR/tls/cert.pem" || ! -f "$ETC_DIR/tls/key.pem" ]]; then
  SAN="DNS:${HOST}"
  if is_ipv4 "$HOST"; then
    SAN="IP:${HOST}"
  fi
  openssl req -x509 -newkey rsa:2048 -sha256 -days 825 -nodes \
    -keyout "$ETC_DIR/tls/key.pem" \
    -out "$ETC_DIR/tls/cert.pem" \
    -subj "/CN=${HOST}" \
    -addext "subjectAltName=${SAN}" 2>/dev/null \
    || openssl req -x509 -newkey rsa:2048 -sha256 -days 825 -nodes \
      -keyout "$ETC_DIR/tls/key.pem" \
      -out "$ETC_DIR/tls/cert.pem" \
      -subj "/CN=${HOST}"
fi

FINGERPRINT="$(openssl x509 -in "$ETC_DIR/tls/cert.pem" -outform DER | sha256sum | awk '{print $1}')"

choose_turns_port

if [[ ! -f "$ETC_DIR/config.json" ]]; then
  SERVER_ID="$(openssl rand -hex 16)"
  SETUP_TOKEN="$(openssl rand -hex 24)"
  TURN_SECRET="$(openssl rand -hex 32)"
  cat > "$ETC_DIR/config.json" <<EOF
{
  "listen": "0.0.0.0:${PORT}",
  "data_dir": "${DATA_DIR}",
  "tls_cert": "${ETC_DIR}/tls/cert.pem",
  "tls_key": "${ETC_DIR}/tls/key.pem",
  "setup_token": "${SETUP_TOKEN}",
  "server_id": "${SERVER_ID}",
  "mailbox_ttl_seconds": 604800,
  "max_envelope_bytes": 65536,
  "allow_http": false,
  "fingerprint": "${FINGERPRINT}",
  "public_host": "${HOST}",
  "turn_secret": "${TURN_SECRET}",
  "turn_port": ${TURN_PORT},
  "turns_port": ${TURNS_PORT}
}
EOF
else
  SETUP_TOKEN="$(json_get "$ETC_DIR/config.json" "setup_token")"
  SERVER_ID="$(json_get "$ETC_DIR/config.json" "server_id")"
  TURN_SECRET="$(json_get "$ETC_DIR/config.json" "turn_secret")"
  if [[ -z "$TURN_SECRET" ]]; then
    TURN_SECRET="$(openssl rand -hex 32)"
  fi
fi

# Persist ICE fields before coturn starts so a bind failure still leaves matching secrets.
write_ice_config "$ETC_DIR/config.json" "$HOST" "$TURN_SECRET" "$TURN_PORT" "$TURNS_PORT"
# Re-read secret in case config already had one.
TURN_SECRET="$(json_get "$ETC_DIR/config.json" "turn_secret")"

chown -R "$SERVICE_USER:$SERVICE_USER" "$DATA_DIR"
chown -R root:"$SERVICE_USER" "$ETC_DIR"
chmod 640 "$ETC_DIR/config.json" "$ETC_DIR/tls/key.pem"
chmod 644 "$ETC_DIR/tls/cert.pem"

UNIT_SRC="$(cd "$(dirname "$0")/.." && pwd)/systemd/rope.service"
if [[ -f "$UNIT_SRC" ]]; then
  install -m 0644 "$UNIT_SRC" /etc/systemd/system/rope.service
else
  cat > /etc/systemd/system/rope.service <<'EOF'
[Unit]
Description=Rope relay server
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=rope
Group=rope
ExecStart=/opt/rope/bin/rope-server --config /etc/rope/config.json
Restart=on-failure
RestartSec=3
NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=strict
ProtectHome=true
ReadWritePaths=/var/lib/rope

[Install]
WantedBy=multi-user.target
EOF
fi

# Starting rope should also start coturn; stopping rope must NOT kill coturn.
mkdir -p /etc/systemd/system/rope.service.d
cat > /etc/systemd/system/rope.service.d/turn.conf <<'EOF'
[Unit]
Wants=coturn.service
After=network-online.target
EOF

write_coturn_dropin() {
  local unit="$1"
  mkdir -p "/etc/systemd/system/${unit}.service.d"
  cat > "/etc/systemd/system/${unit}.service.d/rope.conf" <<'EOF'
[Unit]
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=turnserver
Group=turnserver
Restart=on-failure
RestartSec=3
RuntimeDirectory=turnserver
RuntimeDirectoryMode=0750
AmbientCapabilities=CAP_NET_BIND_SERVICE
CapabilityBoundingSet=CAP_NET_BIND_SERVICE
ExecStart=
ExecStart=/usr/bin/turnserver -c /etc/turnserver.conf --pidfile=/run/turnserver/turnserver.pid --daemon=off
EOF
}

turn_unit() {
  if systemctl list-unit-files coturn.service >/dev/null 2>&1 && \
     systemctl list-unit-files coturn.service 2>/dev/null | grep -q coturn.service; then
    echo coturn
  elif systemctl list-unit-files turnserver.service >/dev/null 2>&1 && \
       systemctl list-unit-files turnserver.service 2>/dev/null | grep -q turnserver.service; then
    echo turnserver
  else
    echo coturn
  fi
}

apply_turn_conf() {
  umask 077
  render_turnserver_conf > /etc/turnserver.conf
  if id -u turnserver >/dev/null 2>&1; then
    chown root:turnserver /etc/turnserver.conf
  else
    chown root:root /etc/turnserver.conf
  fi
  chmod 640 /etc/turnserver.conf
  cp /etc/turnserver.conf "$ETC_DIR/turnserver.conf"
  if id -u turnserver >/dev/null 2>&1; then
    chown root:turnserver "$ETC_DIR/turnserver.conf"
  fi
  chmod 640 "$ETC_DIR/turnserver.conf"
}

coturn_active() {
  systemctl is-active --quiet coturn || systemctl is-active --quiet turnserver
}

restart_coturn() {
  local unit
  unit="$(turn_unit)"
  write_coturn_dropin "$unit"
  if [[ "$unit" == "coturn" ]]; then
    write_coturn_dropin turnserver
  fi
  systemctl daemon-reload || return 1
  systemctl enable "$unit" >/dev/null 2>&1 || true
  systemctl restart "$unit" || return 1
}

listening_on() {
  local p="$1"
  if command -v ss >/dev/null 2>&1; then
    ss -lntun 2>/dev/null | awk '{print $5}' | grep -Eq "[.:]${p}$"
  else
    port_in_use "$p"
  fi
}

install_coturn() {
  if ! command -v turnserver >/dev/null 2>&1; then
    export DEBIAN_FRONTEND=noninteractive
    if command -v apt-get >/dev/null 2>&1; then
      apt-get update -qq
      apt-get install -y -qq coturn
    else
      echo "ROPE_TURN_SKIPPED=no-apt" >&2
      write_turn_status 0 "нет apt, coturn не установлен" "" ""
      return 1
    fi
  fi
  if ! command -v turnserver >/dev/null 2>&1; then
    echo "ROPE_TURN_SKIPPED=no-turnserver" >&2
    write_turn_status 0 "пакет coturn установлен, бинарника turnserver нет" "" ""
    return 1
  fi

  if ! id -u turnserver >/dev/null 2>&1; then
    useradd --system --home /var/lib/turnserver --shell /usr/sbin/nologin turnserver 2>/dev/null || true
  fi
  if id -u turnserver >/dev/null 2>&1; then
    usermod -aG "$SERVICE_USER" turnserver 2>/dev/null || true
  fi

  mkdir -p "$ETC_DIR/turn-tls" /var/log/turnserver /var/lib/turnserver
  local cert_user=root
  local cert_group="$SERVICE_USER"
  if id -u turnserver >/dev/null 2>&1; then
    cert_user=turnserver
    cert_group=turnserver
  fi
  install -o "$cert_user" -g "$cert_group" -m 644 "$ETC_DIR/tls/cert.pem" "$ETC_DIR/turn-tls/cert.pem"
  install -o "$cert_user" -g "$cert_group" -m 640 "$ETC_DIR/tls/key.pem" "$ETC_DIR/turn-tls/key.pem"
  if id -u turnserver >/dev/null 2>&1; then
    chown turnserver:turnserver /var/log/turnserver /var/lib/turnserver 2>/dev/null || true
  fi

  if [[ -f /etc/default/coturn ]]; then
    if grep -q '^TURNSERVER_ENABLED=' /etc/default/coturn; then
      sed -i 's/^TURNSERVER_ENABLED=.*/TURNSERVER_ENABLED=1/' /etc/default/coturn
    else
      echo "TURNSERVER_ENABLED=1" >> /etc/default/coturn
    fi
  else
    echo "TURNSERVER_ENABLED=1" > /etc/default/coturn
  fi

  apply_turn_conf
  if ! restart_coturn; then
    echo "coturn restart failed on TURNS ${TURNS_PORT}" >&2
  fi

  if ! coturn_active && [[ "$TURNS_PORT" == "443" ]]; then
    echo "TURNS 443 bind failed; falling back to 5349" >&2
    TURNS_PORT="5349"
    write_ice_config "$ETC_DIR/config.json" "$HOST" "$TURN_SECRET" "$TURN_PORT" "$TURNS_PORT"
    apply_turn_conf
    restart_coturn || true
  fi

  if ! coturn_active && [[ "$TURNS_PORT" == "5349" ]]; then
    echo "TURNS 5349 bind failed; advertising UDP/TCP 3478 only" >&2
    TURNS_PORT="0"
    write_ice_config "$ETC_DIR/config.json" "$HOST" "$TURN_SECRET" "$TURN_PORT" "$TURNS_PORT"
    apply_turn_conf
    restart_coturn || true
  fi

  local ext
  ext="$(external_ip_line | sed 's/^external-ip=//')"
  if coturn_active && listening_on "$TURN_PORT"; then
    write_ice_config "$ETC_DIR/config.json" "$HOST" "$TURN_SECRET" "$TURN_PORT" "$TURNS_PORT"
    write_turn_status 1 "" "0.0.0.0" "$ext"
    echo "ROPE_TURN_OK"
    echo "TURN_PORT=${TURN_PORT}"
    echo "TURNS_PORT=${TURNS_PORT}"
    echo "TURN_LISTEN=0.0.0.0"
    echo "TURN_EXTERNAL_IP=${ext}"
    return 0
  fi

  local err="coturn не запустился"
  if ! command -v turnserver >/dev/null 2>&1; then
    err="нет turnserver"
  elif foreign_tcp_port "$TURN_PORT"; then
    err="порт ${TURN_PORT} занят"
  elif [[ "$TURNS_PORT" != "0" ]] && foreign_tcp_port "$TURNS_PORT"; then
    err="TURNS порт ${TURNS_PORT} занят"
  elif [[ ! -f "$ETC_DIR/turn-tls/cert.pem" || ! -f "$ETC_DIR/turn-tls/key.pem" ]]; then
    err="нет TLS-сертификата для TURNS"
  else
    err="coturn inactive (смотрите journalctl -u coturn)"
  fi
  echo "ROPE_TURN_SKIPPED=inactive" >&2
  echo "ROPE_TURN_ERROR=${err}" >&2
  systemctl status coturn --no-pager >&2 || systemctl status turnserver --no-pager >&2 || true
  write_turn_status 0 "$err" "" "$ext"
  return 1
}

TURN_OK=0
TURN_ERROR=""
if install_coturn; then
  TURN_OK=1
else
  TURN_ERROR="coturn not running"
  echo "coturn not running; GET /v1/info still advertises ICE if turn_secret is set" >&2
fi

# Re-read ports after possible 443→5349 fallback.
TURN_PORT="$(json_get "$ETC_DIR/config.json" "turn_port")"
TURNS_PORT="$(json_get "$ETC_DIR/config.json" "turns_port")"
[[ -n "$TURN_PORT" ]] || TURN_PORT="3478"

if command -v ufw >/dev/null 2>&1; then
  ufw allow "${PORT}/tcp" >/dev/null 2>&1 || true
  ufw allow "${TURN_PORT}/tcp" >/dev/null 2>&1 || true
  ufw allow "${TURN_PORT}/udp" >/dev/null 2>&1 || true
  ufw allow "443/tcp" >/dev/null 2>&1 || true
  ufw allow "5349/tcp" >/dev/null 2>&1 || true
  ufw allow "${RELAY_MIN}:${RELAY_MAX}/udp" >/dev/null 2>&1 || true
fi

chmod 640 "$ETC_DIR/config.json"
systemctl daemon-reload
# enable --now does not replace a running binary; always restart so turn_secret is loaded.
systemctl enable rope >/dev/null 2>&1 || true
systemctl restart rope

for i in 1 2 3 4 5 6 7 8 9 10; do
  if curl -ksS "https://127.0.0.1:${PORT}/health" | grep -q '"ok"'; then
    break
  fi
  sleep 1
done

if ! curl -ksS "https://127.0.0.1:${PORT}/health" | grep -q '"ok"'; then
  echo "health check failed" >&2
  systemctl status rope --no-pager || true
  exit 1
fi

if [[ "$already_installed" -eq 1 || "$UPGRADE" -eq 1 ]]; then
  echo "upgraded binary; data and config preserved"
  echo "ROPE_UPGRADE_OK"
  if [[ "$TURN_OK" -eq 1 ]]; then
    echo "ROPE_TURN_OK"
    echo "TURN_PORT=${TURN_PORT}"
    echo "TURNS_PORT=${TURNS_PORT}"
  else
    echo "ROPE_TURN_SKIPPED=inactive"
    [[ -n "$TURN_ERROR" ]] && echo "ROPE_TURN_ERROR=${TURN_ERROR}"
  fi
  exit 0
fi

echo "ROPE_INSTALL_OK"
echo "HOST=${HOST}"
echo "PORT=${PORT}"
echo "SERVER_ID=${SERVER_ID}"
echo "FINGERPRINT=${FINGERPRINT}"
echo "SETUP_TOKEN=${SETUP_TOKEN}"
if [[ "$TURN_OK" -eq 1 ]]; then
  echo "ROPE_TURN_OK"
  echo "TURN_PORT=${TURN_PORT}"
  echo "TURNS_PORT=${TURNS_PORT}"
else
  echo "ROPE_TURN_SKIPPED=inactive"
fi
